#!/bin/sh

PYPATH=/usr/include/python2.4/

echo "Calling swig"
swig -nodirprot -makedefault `pkg-config dataharvester --cflags` `pkg-config rave --cflags` -v -c++ -python vertigo.i

echo "Now compiling vertigo wrapper"
g++ -Wall -fpic -c vertigo_wrap.cxx -I/usr/java/include -I$PYPATH -I. `pkg-config rave --cflags` `pkg-config dataharvester --cflags`

g++ -Wall -shared -fpic vertigo_wrap.o -Lbuild/Vertigo -lVertigo -Lbuild/CMSSkin -lCMSSkin -Lbuild/DummySkin -lDummySkin -Lbuild/LDCSkin -lLDCSkin -Lbuild/SIDSkin -lSIDSkin -Lbuild/Environment -lVertigoEnvironment -Lbuild/Analysis -lVertigoAnalysis -o _vertigo.so `pkg-config rave --libs` `pkg-config dataharvester --libs`
