Document: vertigo
Title: Debian vertigo Manual
Author: <insert document author here>
Abstract: This manual describes what vertigo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vertigo/vertigo.sgml.gz

Format: postscript
Files: /usr/share/doc/vertigo/vertigo.ps.gz

Format: text
Files: /usr/share/doc/vertigo/vertigo.text.gz

Format: HTML
Index: /usr/share/doc/vertigo/html/index.html
Files: /usr/share/doc/vertigo/html/*.html

  
